export const MAP_ACTION_FETCH_DATA_BEGIN = 'MAP_ACTION_FETCH_DATA_BEGIN';
export const MAP_ACTION_FETCH_DATA_SUCCESS = 'MAP_ACTION_FETCH_DATA_SUCCESS';
export const MAP_ACTION_FETCH_DATA_FAILURE = 'MAP_ACTION_FETCH_DATA_FAILURE';
export const MAP_ACTION_FETCH_DATA_DISMISS_ERROR = 'MAP_ACTION_FETCH_DATA_DISMISS_ERROR';
